name: Unit Tests

on:
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: test
        run: yarn test
